defaults:
  - override /hydra/launcher: submitit_local # change to submitit_slurm when working on a slurm cluster

task_name : "test_hydra"

param1: 1
param2: 13

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 60
    cpus_per_task: 2
    gpus_per_node: 0
    tasks_per_node: 1
    mem_gb: 4
    nodes: 1
    name: ${hydra.job.name}